# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
name: Java springboot app
on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
    inputs:
      # logLevel:
      #   description: 'Log level'
      #   required: true
      #   default: 'warning'
      environment:
        description: 'Environment to deploy'
        required: false
        default: 'staging'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo "Pipelin run for ${{ github.event.inputs.environment }} environment!"
      
    - name : Git Checkout
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Code Compile
      run: mvn clean compile

    - name: Unit Testing
      run: mvn test
    
    - name: Build with Maven
      run: mvn clean install

    - name: Build the Docker image
      run: docker build --file Dockerfile -t petclinic .

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        # Username used to log against the Docker registry
        username: # optional
        # Password or personal access token used to log against the Docker registry
        password: # optional
        # Specifies whether the given registry is ECR (auto, true or false)
        ecr: # optional, default is auto
        # Log out from the Docker registry at the end of a job
        logout: # optional, default is true
          
