# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
name: Java springboot app
on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: false
        default: 'staging'

jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo "Pipeline run for ${{ github.event.inputs.environment }} environment!"
      
    - name : Git Checkout
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
  
    - name: Code Compile
      run: mvn clean compile

    - name: Unit Testing
      run: mvn test
    
    - name: Build with Maven
      run: mvn clean install
    
    - name: Save WAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: application-war
        path: target/*.war
        if-no-files-found: warn

  docker-build:
    runs-on: ubuntu-latest
    needs: maven-build
    steps:
    - name: Download WAR artifact
      uses: actions/download-artifact@v4
      with:
        name: application-war

    - name: List files in the workspace
      run: ls -al

    - name: Build the Docker image
      run: docker build --file Dockerfile -t xedose/petclinic .

    - name: Docker Hub Login
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}

    - name: Push to Docker Hub
      run: docker push xedose/petclinic
